version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
  - object: /home/ec2-user/setup.sh
    mode: 777
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: root